### ISSUE TITLE
libpng 问题

### ISSUE THREAD

**Issue by WayneZhouChina** [vincascm/qrencode#1]
报错信息：
libpng warning: Application built with libpng-1.2.49 but running with 1.6.10
Failed to initialize PNG writer.
nil	Failed to encode the input data to png

你好，上面是报错信息。请问qrencode 只能是用 libpng 1.6.10 吗？

**Comment by WayneZhouChina** [comment]
装了 libpng 1.6 这个问题没有了。

**Comment by WayneZhouChina** [comment]
貌似还是 libpng 的问题，是必须用 1.6.10 这个版本吗？我安装了 1.6.xx 这个版本，貌似还是不行。strace 跟了一下是可以找到 libpng16.so.16 这个库的，open("/usr/local/lib64/libpng16.so.16", O_RDONLY) = 3。请帮忙看下？不知道能否给个联系方式

**Comment by vincascm** [comment]
```libpng warning: Application built with libpng-1.2.49 but running with 1.6.10```
看这条信息，应该是编译问题，编译信息是1.2.49，动态链接(.so文件)是1.6.10
@WayneZhouChina
