### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by wang-changqing** [vincascm/qrencode#3]
再Chrome下面不能显示二维码
default_type image/png;
add_header Expires "Fri, 01 Jan 1980 00:00:00 GMT";
add_header Pragma "no-cache";
add_header Cache-Control "no-cache, max-age=0, must-revalidate";
以上设置都添加了，在IE浏览器上没问题

**Comment by vincascm** [comment]
@wang-changqing 看日志，access_log,errors_log

**Comment by vincascm** [comment]
@wang-changqing 新请求在access日志里出现吗，没有的话有缓存

**Comment by wang-changqing** [comment]
出现了，没有缓存，目前问题是在IE浏览器上显示正常，在Chrome上显示乱码。

**Comment by vincascm** [comment]
@wang-changqing 
```lua
ngx.header.content_type = 'image/png'
ngx.say(
  qr {
    text = vcard .. "END:VCARD",
    size = args.size or 8,
    margin = args.margin or 0,
    symversion = 2,
    level = 'M',
    foreground = args.fg,
    background = args.bg
  }
)
```

**Comment by wang-changqing** [comment]
@vincascm 问题已解决，感谢。后期能不能写个教程介绍下里面的参数呢。
