### ISSUE TITLE
关于openwrt上Phantun的配置问题

### ISSUE THREAD

**Issue by ibeange** [vincascm/qrencode#5]
开发者你好，抱歉在这个项目下提issue，因为我没有其他地方能联系到你。
我通过google搜索到你的博客，看到你有在openwrt上部署phantun，我也有相同需求，但是按照你博客中的教程无法实现想要的结果，若你有时间，望能给点指导，非常感谢！

**Comment by vincascm** [comment]
很乐意探讨一些技术问题，可以在[这里](https://github.com/dndx/phantun/issues/116)继续
